//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.370.0.
namespace Spec.DD.DC
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.370.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Font", Namespace="http://www.omg.org/spec/DD/20100524/DC")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Font", Namespace="http://www.omg.org/spec/DD/20100524/DC")]
    public partial class Font
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("name")]
        public string Name { get; set; }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlAttributeAttribute("size")]
        public double SizeValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Size-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the Size property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool SizeValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<double> Size
        {
            get
            {
                if (this.SizeValueSpecified)
                {
                    return this.SizeValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.SizeValue = value.GetValueOrDefault();
                this.SizeValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlAttributeAttribute("isBold")]
        public bool IsBoldValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die IsBold-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IsBold property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool IsBoldValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> IsBold
        {
            get
            {
                if (this.IsBoldValueSpecified)
                {
                    return this.IsBoldValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IsBoldValue = value.GetValueOrDefault();
                this.IsBoldValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlAttributeAttribute("isItalic")]
        public bool IsItalicValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die IsItalic-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IsItalic property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool IsItalicValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> IsItalic
        {
            get
            {
                if (this.IsItalicValueSpecified)
                {
                    return this.IsItalicValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IsItalicValue = value.GetValueOrDefault();
                this.IsItalicValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlAttributeAttribute("isUnderline")]
        public bool IsUnderlineValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die IsUnderline-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IsUnderline property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool IsUnderlineValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> IsUnderline
        {
            get
            {
                if (this.IsUnderlineValueSpecified)
                {
                    return this.IsUnderlineValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IsUnderlineValue = value.GetValueOrDefault();
                this.IsUnderlineValueSpecified = value.HasValue;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        [System.Xml.Serialization.XmlAttributeAttribute("isStrikeThrough")]
        public bool IsStrikeThroughValue { get; set; }
        
        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die IsStrikeThrough-Eigenschaft spezifiziert ist, oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets a value indicating whether the IsStrikeThrough property is specified.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]
        public bool IsStrikeThroughValueSpecified { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public System.Nullable<bool> IsStrikeThrough
        {
            get
            {
                if (this.IsStrikeThroughValueSpecified)
                {
                    return this.IsStrikeThroughValue;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.IsStrikeThroughValue = value.GetValueOrDefault();
                this.IsStrikeThroughValueSpecified = value.HasValue;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.370.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Point", Namespace="http://www.omg.org/spec/DD/20100524/DC")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Point", Namespace="http://www.omg.org/spec/DD/20100524/DC")]
    public partial class Point
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("x")]
        public double X { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("y")]
        public double Y { get; set; }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.370.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Bounds", Namespace="http://www.omg.org/spec/DD/20100524/DC")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Bounds", Namespace="http://www.omg.org/spec/DD/20100524/DC")]
    public partial class Bounds
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute("x")]
        public double X { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("y")]
        public double Y { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("width")]
        public double Width { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute("height")]
        public double Height { get; set; }
    }
}
